# Generated by Django 5.2.11 on 2026-04-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genre',
            field=models.CharField(choices=[('sci_fi', 'Sci-Fi'), ('romance', 'Romance'), ('drama', 'Drama'), ('accion', 'Acción'), ('comedia', 'Comedia'), ('terror', 'Terror'), ('aventura', 'Aventura'), ('fantasia', 'Fantasía'), ('animacion', 'Animación'), ('documental', 'Documental'), ('musical', 'Musical'), ('thriller', 'Thriller')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
