# Generated by Django 5.2.11 on 2026-05-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0002_alter_pelicula_genre_alter_pelicula_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
