# Generated by Django 5.2.11 on 2026-05-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_infopersonal_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='usuarios/default-user-pfp.png', null=True, upload_to='usuarios/'),
        ),
    ]
