# Generated by Django 5.2.11 on 2026-05-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_customuser_bio_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
